apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scc-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1G"
  storageClassName: netapp-nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-deployment
  labels:
    app: scc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scc
  template:
    metadata:
      labels:
        app: scc
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: scc-volume
          persistentVolumeClaim:
            claimName: scc-pv-claim
      containers:
        - name: scc
          image: ghcr.io/theplenkov/sap-cloud-connector:latest
          # command: ["/bin/sh"]
          # args:
          #   ["-c", "sleep 1000 && echo Sleep expired > /dev/termination-log"]
          ports:
            - containerPort: 8443
          resources:
            limits:
              cpu: "0.5"
              memory: "1G"
          volumeMounts:
            - mountPath: "/scc"
              name: scc-volume
---
apiVersion: v1
kind: Service
metadata:
  name: scc-service
  labels:
    app: scc
spec:
  type: ClusterIP
  ports:
    - name: scc-port
      port: 443
      targetPort: 8443
  selector:
    app: scc
